### PR TITLE
Added support for more spinner types and custom spinners.

### PR DESCRIPTION
**Pull request by smk508**
I incorporated a bunch of spinner types I found here: https://github.com/molovo/revolver 

The spinner type can be specified via the optional spinner_type argument, and you can also provide your own spinner as a list to the optional custom_spinner argument. 

I could only get this to work with the single-character spinners; some of the spinners have multiple characters and those don't print properly, so I left them out.

### CODE REVIEW

**Comment by yoavram** [comment]
First, thanks for contributing!

Second, I'm not sure I want to incorporate additional spinners, but let's discuss it:
My fear is that adding more spinners will make it harder to maintain, support, and extend this package.
Maybe it would be better if you create a fork titled "click-multi-spinner" or something like that?

What do you think?

**Comment by smk508** [comment]
Hi @yoavram . Thanks for considering my PR! 

I don't think it would make it meaningfully harder to support the package, because we're just changing the characters that the spinner iterates between. I don't have a deeper knowledge of unicode, so I'm not aware of what challenges this would lead to. Do you have a sense of what issues you foresee? I think if it really would make this package much harder to maintain, then a fork would make more sense.

But if not, I think if would be convenient to have an aesthetic feature like this be part of the main package as an option, so people can make their CLIs have crazy spinners if they want.

**Comment by yoavram** [comment]
Some comments:
- [ ] I got a warning that the escaping in the `flip` spinner type is deprecated, please just use `r"`"`, and `r"`"`.
- [ ] could you add an example of using these spinner types in the docstring?
- [ ] could you add some tests?
- [ ] the `spinner_types` dict should be `_spinner_types`
- [ ] How is someone supposed to know all the spinner types? Read the code?? Maybe add a function that returns all the spinner types? something like this: `def spinner_types(): return tuple(_spinner_types.keys())`
- [ ] what happens if I use the wrong spinner type name? currently I just get a `KeyError`, but this is not a good behaviour, I don't think.

**Comment by yoavram** [comment]
Closing - @smk58 please reopen if you want to address the questions above.

**Pull request closed without merging**
