### PR TITLE
PEP 561 Compatible

### PR DESCRIPTION
**Pull request by harens**
Hi there :wave: 

Thanks for the great package. I thought I'd try and make it [PEP 561 Compatible](https://www.python.org/dev/peps/pep-0561) via inline types. This is since I am using click-spinner in one of my projects, but realised that it didn't support type checking.

I also added Format checking via [black](https://github.com/psf/black) and [isort](https://github.com/PyCQA/isort) to the travis file. Let me know if anything's not right and I'll be happy to change it. Thanks.

### CODE REVIEW

**Comment by harens** [comment]
Dang :facepalm:. Just realised that python 2.7 and 3.4 and still supported (which makes sense since click supports them), so I presume the tests will fail for them since the inline syntax wasn't added until 3.6. 

Might be worth redoing it with Python 2 function type annotation syntax.

**Comment by harens** [comment]
So it turns out that some of the syntax I used is python 3.8+ only (such as [typeddict](https://www.python.org/dev/peps/pep-0589/) and [literal](https://www.python.org/dev/peps/pep-0586/)). It might be more useful to instead submit this to the [python/typeshed](https://github.com/python/typeshed) repo, since then large changes do not have to be made to your codebase.

Would this be ok with yourself?

**Comment by yoavram** [comment]
@harens fine with me

**Comment by harens** [comment]
[Here's the result](https://github.com/python/typeshed/blob/master/third_party/2and3/click_spinner/__init__.pyi). This means that click-spinner now has complete type annotations that can be used by tools that use typeshed (e.g. mypy, pytype, PyCharm, etc.). This should help to improve the experience of using click-spinner with different linters and IDEs.

It might be useful to document this, but I'll leave that to your judgement. Thanks again for maintaining this project.

**Comment by yoavram** [comment]
If you can add some documentation as PR I'd be happy to accept it.

**Pull request closed without merging**
